### ISSUE TITLE
cli.py does nothing

### ISSUE THREAD

**Issue by alexgranford** [guilhermef/pi_weatherstation#1]
Got everything installed, but running `python cli.py` returns nothing, verbose debug is not helping either.

Can you possibly give some simple usage examples.

**Comment by guilhermef** [comment]
Hi @alexgranford, this project is still under development, I'll add the steps to run it today.

**Comment by alexgranford** [comment]
Perfect, thanks @guilhermef, I will be feedbacking if you don't mind as we get along, I've got both BME680 and ST7789.

**Comment by guilhermef** [comment]
I've added the steps to the README, I'll be improving the code during this week and I'll opensource a case for people to 3D print.

**Comment by alexgranford** [comment]
thanks, the steps worked fine, great work!
